import { Level } from './types';

export const levels: Level[] = [
  {
    id: 1,
    name: 'The Hallway',
    nodes: [
      { id: 'a', x: 100, y: 300 },
      { id: 'b', x: 250, y: 300 },
      { id: 'c', x: 400, y: 300 },
      { id: 'd', x: 550, y: 300 },
      { id: 'e', x: 700, y: 300 },
    ],
    edges: [
      { from: 'a', to: 'b' },
      { from: 'b', to: 'c' },
      { from: 'c', to: 'd' },
      { from: 'd', to: 'e' },
    ],
    playerStart: 'a',
    exit: 'e',
    enemies: [
      { id: 'g1', type: 'patrol', path: ['c', 'd'], startIndex: 1 },
    ],
  },
  {
    id: 2,
    name: 'The Corner',
    nodes: [
      { id: 'a', x: 100, y: 300 },
      { id: 'b', x: 250, y: 300 },
      { id: 'c', x: 400, y: 300 },
      { id: 'd', x: 400, y: 175 },
      { id: 'e', x: 400, y: 425 },
      { id: 'f', x: 550, y: 300 },
      { id: 'g', x: 700, y: 300 },
    ],
    edges: [
      { from: 'a', to: 'b' },
      { from: 'b', to: 'c' },
      { from: 'c', to: 'd' },
      { from: 'c', to: 'e' },
      { from: 'c', to: 'f' },
      { from: 'f', to: 'g' },
    ],
    playerStart: 'a',
    exit: 'g',
    enemies: [
      { id: 'g1', type: 'patrol', path: ['b', 'c', 'f'], startIndex: 0 },
      { id: 'g2', type: 'stationary', path: ['d'], startIndex: 0 },
    ],
  },
  {
    id: 3,
    name: 'The Grid',
    nodes: [
      { id: 'a', x: 100, y: 175 },
      { id: 'b', x: 250, y: 175 },
      { id: 'c', x: 400, y: 175 },
      { id: 'd', x: 100, y: 300 },
      { id: 'e', x: 250, y: 300 },
      { id: 'f', x: 400, y: 300 },
      { id: 'g', x: 100, y: 425 },
      { id: 'h', x: 250, y: 425 },
      { id: 'i', x: 400, y: 425 },
      { id: 'j', x: 550, y: 300 },
      { id: 'k', x: 700, y: 300 },
    ],
    edges: [
      { from: 'a', to: 'b' }, { from: 'b', to: 'c' },
      { from: 'd', to: 'e' }, { from: 'e', to: 'f' },
      { from: 'g', to: 'h' }, { from: 'h', to: 'i' },
      { from: 'a', to: 'd' }, { from: 'd', to: 'g' },
      { from: 'b', to: 'e' }, { from: 'e', to: 'h' },
      { from: 'c', to: 'f' }, { from: 'f', to: 'i' },
      { from: 'f', to: 'j' }, { from: 'j', to: 'k' },
    ],
    playerStart: 'a',
    exit: 'k',
    enemies: [
      { id: 'g1', type: 'patrol', path: ['b', 'e', 'h'], startIndex: 0 },
      { id: 'g2', type: 'patrol', path: ['d', 'e', 'f'], startIndex: 1 },
      { id: 'g3', type: 'stationary', path: ['j'], startIndex: 0 },
    ],
  },
  {
    id: 4,
    name: 'The Crossroads',
    nodes: [
      { id: 'start', x: 100, y: 300 },
      { id: 'n1', x: 250, y: 300 },
      { id: 'n2', x: 400, y: 175 },
      { id: 'n3', x: 400, y: 300 },
      { id: 'n4', x: 400, y: 425 },
      { id: 'n5', x: 550, y: 175 },
      { id: 'n6', x: 550, y: 300 },
      { id: 'n7', x: 550, y: 425 },
      { id: 'n8', x: 700, y: 175 },
      { id: 'n9', x: 700, y: 300 },
      { id: 'exit', x: 700, y: 425 },
    ],
    edges: [
      { from: 'start', to: 'n1' },
      { from: 'n1', to: 'n2' }, { from: 'n1', to: 'n3' }, { from: 'n1', to: 'n4' },
      { from: 'n2', to: 'n5' }, { from: 'n3', to: 'n6' }, { from: 'n4', to: 'n7' },
      { from: 'n5', to: 'n8' }, { from: 'n6', to: 'n9' }, { from: 'n7', to: 'exit' },
      { from: 'n5', to: 'n6' }, { from: 'n6', to: 'n7' },
      { from: 'n8', to: 'n9' }, { from: 'n9', to: 'exit' },
    ],
    playerStart: 'start',
    exit: 'exit',
    enemies: [
      { id: 'g1', type: 'patrol', path: ['n2', 'n5', 'n8'], startIndex: 0 },
      { id: 'g2', type: 'patrol', path: ['n4', 'n7', 'exit'], startIndex: 0 },
      { id: 'g3', type: 'stationary', path: ['n3'], startIndex: 0 },
      { id: 'g4', type: 'patrol', path: ['n6', 'n9'], startIndex: 0 },
    ],
  },
  {
    id: 5,
    name: 'The Embassy',
    nodes: [
      { id: 's', x: 80,  y: 300 },
      { id: 'a', x: 200, y: 175 },
      { id: 'b', x: 200, y: 300 },
      { id: 'c', x: 200, y: 425 },
      { id: 'd', x: 340, y: 175 },
      { id: 'e', x: 340, y: 300 },
      { id: 'f', x: 340, y: 425 },
      { id: 'g', x: 480, y: 175 },
      { id: 'h', x: 480, y: 300 },
      { id: 'i', x: 480, y: 425 },
      { id: 'j', x: 620, y: 175 },
      { id: 'k', x: 620, y: 300 },
      { id: 'l', x: 620, y: 425 },
      { id: 'ex', x: 740, y: 300 },
    ],
    edges: [
      { from: 's', to: 'b' },
      { from: 'a', to: 'b' }, { from: 'b', to: 'c' },
      { from: 'a', to: 'd' }, { from: 'b', to: 'e' }, { from: 'c', to: 'f' },
      { from: 'd', to: 'e' }, { from: 'e', to: 'f' },
      { from: 'd', to: 'g' }, { from: 'e', to: 'h' }, { from: 'f', to: 'i' },
      { from: 'g', to: 'h' }, { from: 'h', to: 'i' },
      { from: 'g', to: 'j' }, { from: 'h', to: 'k' }, { from: 'i', to: 'l' },
      { from: 'j', to: 'k' }, { from: 'k', to: 'l' },
      { from: 'k', to: 'ex' },
    ],
    playerStart: 's',
    exit: 'ex',
    enemies: [
      { id: 'g1', type: 'patrol', path: ['a', 'b', 'c'], startIndex: 0 },
      { id: 'g2', type: 'patrol', path: ['d', 'e', 'f'], startIndex: 1 },
      { id: 'g3', type: 'patrol', path: ['g', 'h', 'i'], startIndex: 0 },
      { id: 'g4', type: 'stationary', path: ['j'], startIndex: 0 },
      { id: 'g5', type: 'patrol', path: ['k', 'l'], startIndex: 0 },
    ],
  },
  {
    id: 6,
    name: 'The Overpass',
    nodes: [
      { id: 's',  x: 80,  y: 300 },
      { id: 'a',  x: 210, y: 300 },
      { id: 'b',  x: 340, y: 175 },
      { id: 'c',  x: 340, y: 425 },
      { id: 'd',  x: 470, y: 175 },
      { id: 'e',  x: 470, y: 425 },
      { id: 'f',  x: 600, y: 300 },
      { id: 'ex', x: 730, y: 300 },
    ],
    edges: [
      { from: 's', to: 'a' },
      { from: 'a', to: 'b' }, { from: 'a', to: 'c' },
      { from: 'b', to: 'd' }, { from: 'c', to: 'e' },
      { from: 'd', to: 'f' }, { from: 'e', to: 'f' },
      { from: 'f', to: 'ex' },
    ],
    playerStart: 's',
    exit: 'ex',
    enemies: [
      { id: 'g1', type: 'patrol',     path: ['b', 'd'],      startIndex: 0 },
      { id: 'g2', type: 'patrol',     path: ['c', 'e'],      startIndex: 0 },
      { id: 'g3', type: 'stationary', path: ['f'],           startIndex: 0 },
    ],
  },
  {
    id: 7,
    name: 'The T-Bone',
    nodes: [
      { id: 's',  x: 80,  y: 300 },
      { id: 'a',  x: 210, y: 300 },
      { id: 'b',  x: 340, y: 175 },
      { id: 'c',  x: 340, y: 300 },
      { id: 'd',  x: 340, y: 425 },
      { id: 'e',  x: 470, y: 300 },
      { id: 'ex', x: 600, y: 300 },
    ],
    edges: [
      { from: 's', to: 'a' },
      { from: 'a', to: 'b' }, { from: 'a', to: 'c' }, { from: 'a', to: 'd' },
      { from: 'b', to: 'c' }, { from: 'c', to: 'd' },
      { from: 'c', to: 'e' }, { from: 'e', to: 'ex' },
    ],
    playerStart: 's',
    exit: 'ex',
    enemies: [
      { id: 'g1', type: 'patrol',     path: ['b', 'c', 'd'], startIndex: 0 },
      { id: 'g2', type: 'patrol',     path: ['a', 'c', 'e'], startIndex: 1 },
      { id: 'g3', type: 'stationary', path: ['e'],           startIndex: 0 },
    ],
  },
  {
    id: 8,
    name: 'The Loop',
    nodes: [
      { id: 's',  x: 80,  y: 300 },
      { id: 'a',  x: 210, y: 175 },
      { id: 'b',  x: 340, y: 175 },
      { id: 'c',  x: 470, y: 175 },
      { id: 'd',  x: 210, y: 300 },
      { id: 'e',  x: 340, y: 300 },
      { id: 'f',  x: 470, y: 300 },
      { id: 'g',  x: 210, y: 425 },
      { id: 'h',  x: 340, y: 425 },
      { id: 'i',  x: 470, y: 425 },
      { id: 'ex', x: 600, y: 300 },
    ],
    edges: [
      { from: 's', to: 'd' },
      { from: 'a', to: 'b' }, { from: 'b', to: 'c' },
      { from: 'a', to: 'd' }, { from: 'b', to: 'e' }, { from: 'c', to: 'f' },
      { from: 'd', to: 'e' }, { from: 'e', to: 'f' },
      { from: 'd', to: 'g' }, { from: 'e', to: 'h' }, { from: 'f', to: 'i' },
      { from: 'g', to: 'h' }, { from: 'h', to: 'i' },
      { from: 'f', to: 'ex' }, { from: 'i', to: 'ex' },
    ],
    playerStart: 's',
    exit: 'ex',
    enemies: [
      { id: 'g1', type: 'patrol',     path: ['a', 'b', 'c'], startIndex: 0 },
      { id: 'g2', type: 'patrol',     path: ['g', 'h', 'i'], startIndex: 2 },
      { id: 'g3', type: 'patrol',     path: ['d', 'e', 'f'], startIndex: 1 },
      { id: 'g4', type: 'stationary', path: ['c'],           startIndex: 0 },
    ],
  },
  {
    id: 9,
    name: 'The Pincer',
    nodes: [
      { id: 's',  x: 80,  y: 300 },
      { id: 'a',  x: 200, y: 175 },
      { id: 'b',  x: 200, y: 300 },
      { id: 'c',  x: 200, y: 425 },
      { id: 'd',  x: 340, y: 175 },
      { id: 'e',  x: 340, y: 300 },
      { id: 'f',  x: 340, y: 425 },
      { id: 'g',  x: 480, y: 175 },
      { id: 'h',  x: 480, y: 300 },
      { id: 'i',  x: 480, y: 425 },
      { id: 'ex', x: 600, y: 300 },
    ],
    edges: [
      { from: 's', to: 'b' },
      { from: 'a', to: 'b' }, { from: 'b', to: 'c' },
      { from: 'a', to: 'd' }, { from: 'b', to: 'e' }, { from: 'c', to: 'f' },
      { from: 'd', to: 'e' }, { from: 'e', to: 'f' },
      { from: 'd', to: 'g' }, { from: 'e', to: 'h' }, { from: 'f', to: 'i' },
      { from: 'g', to: 'h' }, { from: 'h', to: 'i' },
      { from: 'h', to: 'ex' },
    ],
    playerStart: 's',
    exit: 'ex',
    enemies: [
      { id: 'g1', type: 'patrol',     path: ['a', 'd', 'g'], startIndex: 0 },
      { id: 'g2', type: 'patrol',     path: ['c', 'f', 'i'], startIndex: 0 },
      { id: 'g3', type: 'patrol',     path: ['b', 'e', 'h'], startIndex: 1 },
      { id: 'g4', type: 'stationary', path: ['g'],           startIndex: 0 },
    ],
  },
  {
    id: 10,
    name: 'The Watch Post',
    nodes: [
      { id: 's',  x: 80,  y: 300 },
      { id: 'a',  x: 210, y: 300 },
      { id: 'b',  x: 340, y: 175 },
      { id: 'c',  x: 340, y: 300 },
      { id: 'd',  x: 340, y: 425 },
      { id: 'e',  x: 470, y: 175 },
      { id: 'f',  x: 470, y: 300 },
      { id: 'g',  x: 470, y: 425 },
      { id: 'h',  x: 600, y: 300 },
      { id: 'ex', x: 730, y: 300 },
    ],
    edges: [
      { from: 's', to: 'a' },
      { from: 'a', to: 'b' }, { from: 'a', to: 'c' }, { from: 'a', to: 'd' },
      { from: 'b', to: 'e' }, { from: 'c', to: 'f' }, { from: 'd', to: 'g' },
      { from: 'e', to: 'f' }, { from: 'f', to: 'g' },
      { from: 'e', to: 'h' }, { from: 'f', to: 'h' }, { from: 'g', to: 'h' },
      { from: 'h', to: 'ex' },
    ],
    playerStart: 's',
    exit: 'ex',
    enemies: [
      { id: 'g1',  type: 'patrol',     path: ['a', 'c', 'f'], startIndex: 0 },
      { id: 'sn1', type: 'sniper',     path: ['b'],           startIndex: 0 },
      { id: 'g2',  type: 'patrol',     path: ['d', 'g', 'h'], startIndex: 0 },
      { id: 'g3',  type: 'stationary', path: ['e'],           startIndex: 0 },
    ],
  },
  {
    id: 11,
    name: 'The Compound',
    nodes: [
      { id: 's',  x: 80,  y: 300 },
      { id: 'a',  x: 200, y: 175 },
      { id: 'b',  x: 200, y: 300 },
      { id: 'c',  x: 200, y: 425 },
      { id: 'd',  x: 340, y: 175 },
      { id: 'e',  x: 340, y: 300 },
      { id: 'f',  x: 340, y: 425 },
      { id: 'g',  x: 480, y: 175 },
      { id: 'h',  x: 480, y: 300 },
      { id: 'i',  x: 480, y: 425 },
      { id: 'j',  x: 620, y: 175 },
      { id: 'k',  x: 620, y: 300 },
      { id: 'l',  x: 620, y: 425 },
      { id: 'ex', x: 740, y: 300 },
    ],
    edges: [
      { from: 's', to: 'b' },
      { from: 'a', to: 'b' }, { from: 'b', to: 'c' },
      { from: 'a', to: 'd' }, { from: 'b', to: 'e' }, { from: 'c', to: 'f' },
      { from: 'd', to: 'e' }, { from: 'e', to: 'f' },
      { from: 'd', to: 'g' }, { from: 'e', to: 'h' }, { from: 'f', to: 'i' },
      { from: 'g', to: 'h' }, { from: 'h', to: 'i' },
      { from: 'g', to: 'j' }, { from: 'h', to: 'k' }, { from: 'i', to: 'l' },
      { from: 'j', to: 'k' }, { from: 'k', to: 'l' },
      { from: 'k', to: 'ex' },
    ],
    playerStart: 's',
    exit: 'ex',
    enemies: [
      { id: 'g1',  type: 'patrol',  path: ['a', 'b', 'c'], startIndex: 0 },
      { id: 'g2',  type: 'patrol',  path: ['d', 'e', 'f'], startIndex: 1 },
      { id: 'g3',  type: 'patrol',  path: ['g', 'h', 'i'], startIndex: 0 },
      { id: 'sn1', type: 'sniper',  path: ['j'],           startIndex: 0 },
      { id: 'g4',  type: 'patrol',  path: ['k', 'l'],      startIndex: 1 },
    ],
  },
  {
    id: 12,
    name: 'The Finale',
    nodes: [
      { id: 's',  x: 80,  y: 300 },
      { id: 'a',  x: 200, y: 175 },
      { id: 'b',  x: 200, y: 300 },
      { id: 'c',  x: 200, y: 425 },
      { id: 'd',  x: 340, y: 175 },
      { id: 'e',  x: 340, y: 300 },
      { id: 'f',  x: 340, y: 425 },
      { id: 'g',  x: 480, y: 175 },
      { id: 'h',  x: 480, y: 300 },
      { id: 'i',  x: 480, y: 425 },
      { id: 'j',  x: 620, y: 300 },
      { id: 'ex', x: 740, y: 300 },
    ],
    edges: [
      { from: 's', to: 'b' },
      { from: 'a', to: 'b' }, { from: 'b', to: 'c' },
      { from: 'a', to: 'd' }, { from: 'b', to: 'e' }, { from: 'c', to: 'f' },
      { from: 'd', to: 'e' }, { from: 'e', to: 'f' },
      { from: 'd', to: 'g' }, { from: 'e', to: 'h' }, { from: 'f', to: 'i' },
      { from: 'g', to: 'h' }, { from: 'h', to: 'i' },
      { from: 'g', to: 'j' }, { from: 'h', to: 'j' }, { from: 'i', to: 'j' },
      { from: 'j', to: 'ex' },
    ],
    playerStart: 's',
    exit: 'ex',
    enemies: [
      { id: 'g1',  type: 'patrol',  path: ['a', 'b', 'c'], startIndex: 1 },
      { id: 'g2',  type: 'patrol',  path: ['f', 'e', 'd'], startIndex: 0 },
      { id: 'g3',  type: 'patrol',  path: ['g', 'h', 'i'], startIndex: 2 },
      { id: 'sn1', type: 'sniper',  path: ['d'],           startIndex: 0 },
      { id: 'g4',  type: 'patrol',  path: ['h', 'j'],      startIndex: 0 },
    ],
  },
];
